[x-axis]
where = top

[spacer]
height = 0.5

#==================================
# GENE TRACK
#==================================
[genes]
file = genes.gtf
height = 3
title = Genes
fontsize = 10
file_type = gtf
prefered_name = gene_name
merge_transcripts = true
style = UCSC

[spacer]
height = 0.8

#==================================
# 6mA - LOY SAMPLES (Blue #0000C0) vs ROY samples (Orange #ED7D31)
#==================================
[LOY]
file = LOY_average_track.bw
height = 1.5
title = LOY
color = #0000C0
min_value = 0
max_value = 0.15

[ROY]
file = ROY_average_track.bw
height = 1.5
title = ROY
color = #ED7D31
min_value = 0
max_value = 0.15


[spacer]
height = 0.5

